### ISSUE TITLE
commute to global

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/flocks.js#27]
@Glenjamin recommends to move the library off of `window` into a global, to make referring to it more convenient.  I agree, and will do so.

**Comment by glenjamin** [comment]
Not quite what I meant:

when including directly into the browser, attaching to the global (ie. window) is perfectly sensible.

In the example here: http://www.flocks.rocks/what_is_flocks.html#tiny you should just access flocks as `flocksjs2` rather than `window.flocksjs2`.

This separates the usage example from the include mechanism, and means the example will copy-paste into AMD or CommonJS environments.

**Comment by StoneCypher** [comment]
Oh.

... huh.

**Comment by StoneCypher** [comment]
Done in testing app.  Will commute to flocks rocks repo momentarily.
